[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-inertia"
version = "0.1.0"
description = """
An implementation of the Inertia protocol for FastAPI.
"""

[tool.mypy]
strict = true
check_untyped_defs = true
ignore_missing_imports = true
